version: '3.8'

services:
  mapasculturais:
    image: efcjunior/mapasculturais:prefeitura-triunfo
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - REDIS_CACHE=redis
      - SESSIONS_SAVE_PATH=tcp://sessions:6379
    depends_on:
      - db
      - redis
      - sessions
    command: ["sh", "-c", "nginx && php-fpm"]
    volumes:
      - sessions-data:/var/www/var/sessions

  redis:
    image: redis:6
    command: --maxmemory 1256Mb --maxmemory-policy allkeys-lru
    restart: unless-stopped

  sessions:
    image: redis:6
    command: --maxmemory 384Mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    volumes:
      - sessions-data:/data

  db:
    image: efcjunior/mapasculturais-postgis:mapasculturais-postgis
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  sessions-data:
  db-data:
