services:
  treina-triunfo-mapa-mapasculturais:
    image: efcjunior/mapasculturais:prefeitura-triunfo
    restart: unless-stopped
    environment:
      - REDIS_CACHE=redis
      - SESSIONS_SAVE_PATH=tcp://sessions:6379
    depends_on:
      - treina-triunfo-mapa-db
      - treina-triunfo-mapa-redis
      - treina-triunfo-mapa-sessions
    volumes:
      - treina-triunfo-mapa-sessions-data:/var/www/var/sessions
      - treina-triunfo-mapa-files:/var/www/html/files
      - treina-triunfo-mapa-assets:/var/www/html/assets

  treina-triunfo-mapa-nginx:
    image: efcjunior/mapasculturais:mapasculturais-nginx
    restart: unless-stopped
    depends_on:
      - treina-triunfo-mapa-mapasculturais
    ports:
      - "8080:80"
    volumes:
      - treina-triunfo-mapa-files:/var/www/html/files
      - treina-triunfo-mapa-assets:/var/www/html/assets
      - /dev/null:/var/www/html/index.php  # Substitui index.php por /dev/null

  treina-triunfo-mapa-redis:
    image: redis:6
    command: --maxmemory 1256Mb --maxmemory-policy allkeys-lru
    restart: unless-stopped

  treina-triunfo-mapa-sessions:
    image: redis:6
    command: --maxmemory 384Mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    volumes:
      - treina-triunfo-mapa-sessions-data:/data

  treina-triunfo-mapa-db:
    image: efcjunior/mapasculturais-postgis:mapasculturais-postgis
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    volumes:
      - treina-triunfo-mapa-db-data:/var/lib/postgresql/data

volumes:
  treina-triunfo-mapa-sessions-data:
  treina-triunfo-mapa-db-data:
  treina-triunfo-mapa-files:
  treina-triunfo-mapa-assets:
